src/objects/Bond_Buy__c.object
<CustomObject>
    <description>Bond buys represent a potential purchase for a bond offering that is be pitched to an investor</description>
    <fields>
        <fullName>Bond_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The bond offering being purchased</description>
        <inlineHelpText>The bond offering being purchased</inlineHelpText>
        <label>Bond Offering</label>
        <referenceTo>Bond_Offering__c</referenceTo>
        <relationshipLabel>Bond Buys</relationshipLabel>
        <relationshipName>Bond_Buys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The investor being pitched the bond offering</description>
        <inlineHelpText>The investor being pitched the bond offering</inlineHelpText>
        <label>Investor</label>
        <referenceTo>Investor__c</referenceTo>
        <relationshipLabel>Bond Buys</relationshipLabel>
        <relationshipName>Bond_Buys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the bond buy.  Valid values are Pending, Passed, and Purchased</description>
        <inlineHelpText>The status of the bond buy.  Valid values are Pending, Passed, and Purchased</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The number of $10,000 bond units that are being offered</description>
        <inlineHelpText>The number of $10,000 bond units that are being offered</inlineHelpText>
        <label>Units</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bond Buy</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Bond Buy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bond Buys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bond_Offering__c.object
<CustomObject>
    <description>Bond offerings are bonds that CJ sells to investors on behalf of a client.  Each bond offering is for a total of $1,000,000 and is composed of 1,000 units of $1,000.</description>
    <fields>
        <fullName>Client__c</fullName>
        <description>The Client who is issuing the bond</description>
        <inlineHelpText>The Client who is issuing the bond</inlineHelpText>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Bond Offerings</relationshipLabel>
        <relationshipName>Bond_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>0.06</defaultValue>
        <description>The interest rate for the bond offering</description>
        <inlineHelpText>The interest rate for the bond offering</inlineHelpText>
        <label>Interest Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sales Rep responsible for pitching the bond to potential investors</description>
        <inlineHelpText>The Sales Rep responsible for pitching the bond to potential investors</inlineHelpText>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bond_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units_Pending__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of $1,000 bond units that have been purchased.  This number cannot exceed the 1,000 bond units that are available for each $1,000,000 bond offering (enforced by existing validation rule).</description>
        <inlineHelpText>The total number of $1,000 bond units that have been purchased.  This number cannot exceed the 1,000 bond units that are available for each $1,000,000 bond offering (enforced by existing validation rule).</inlineHelpText>
        <label>Units Pending</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of $1,000 bond units that are being pitched to investors but have not yet been purchased or rejected.  This number can’t exceed twice the number of bond units remaining (enforced by existing validation rule).</description>
        <inlineHelpText>The number of $1,000 bond units that are being pitched to investors but have not yet been purchased or rejected.  This number can’t exceed twice the number of bond units remaining (enforced by existing validation rule).</inlineHelpText>
        <label>Units Sold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bond Offering</label>
    <nameField>
        <label>Bond Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bond Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <description>Clients are companies who hire CJ to get their bonds sold to potential investors.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Investor__c.object
<CustomObject>
    <description>Investors are universities, municipalities, pensions, and hedge funds with whom CJ has a relationship.  CJ pitches investors on purchasing units of bond offerings for their clients.</description>
    <fields>
        <fullName>Bonds_Pitched__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of bonds the client has been pitched.</description>
        <inlineHelpText>The total number of bonds the client has been pitched.</inlineHelpText>
        <label>Bonds Pitched</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bonds_Purchased__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of bonds the client has purchased.</description>
        <inlineHelpText>The total number of bonds the client has purchased.</inlineHelpText>
        <label>Bonds Purchased</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The number of bond units the investor typically purchases per bond offering</description>
        <inlineHelpText>The number of bond units the investor typically purchases per bond offering</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedge Funds</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Investor</label>
    <nameField>
        <label>Investor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/generateTestData.cls
@isTest
public class generateTestData {
	private static List<Schema.PicklistEntry> investorTypePicklistValues = Investor__c.Type__c.getDescribe().getPicklistValues();

	/**
	 * Gets a random integer number between lower (inclusive) and upper (exclusive)
	 */
	public static Integer getRandomInt (Integer lower, Integer upper)
	{
		return Math.round((Math.random() * (upper - lower)) + lower);
	}

	public static String getRandomName() {
		return EncodingUtil.convertToHex(crypto.generateAesKey(128)).substring(1,20);
	}

	public static Investor__c getInvestor() {
		Investor__c investor = new Investor__c();
		investor.Name = getRandomName();
		investor.Type__c = investorTypePicklistValues.get(getRandomInt(0, 3)).getValue();
		investor.Bonds_Pitched__c = 0;
		investor.Bonds_Purchased__c = 0;
		return investor;
	}
	
	public static Investor__c getInvestor(String Type) {
		Investor__c investor = new Investor__c();
		investor.Name = getRandomName();
		investor.Type__c = Type;
		investor.Bonds_Pitched__c = 0;
		investor.Bonds_Purchased__c = 0;
		return investor;
	}
	
	public static Bond_Offering__c getBondOffering(String clientId, Double interestRate, String salesRep) {
		Bond_Offering__c bondOffering = new Bond_Offering__c();
		bondOffering.Client__c = clientId;
		bondOffering.Name = getRandomName();
		bondOffering.Interest_Rate__c = interestRate;
		bondOffering.Sales_Rep__c = salesRep;
		bondOffering.Units_Pending__c = 0;
		bondOffering.Units_Sold__c = 0;
		return bondOffering;
	}

	public static Client__c getClient() {
		return new Client__c(Name = getRandomName());
	}

	public static Bond_Buy__c getBondBuy(String bondOfferingId, String investorId, String status, Double units) {
		Bond_Buy__c bondBuy = new Bond_Buy__c();
		bondBuy.Bond_Offering__c = bondOfferingId;
		bondBuy.Investor__c = investorId;
		bondBuy.Status__c = status;
		bondBuy.Units__c = units;
		return bondBuy;
	}

	public static List<sObject> getMultipleObjects(Map<String, Object> parameters, Schema.SObjectType objectType, Integer quantity) {
		List<sObject> result = new List<sObject>();
		sObject tempObject;
		for (Integer i = 0; i < quantity; i++) {
			if (objectType == Bond_Buy__c.getSObjectType())
				tempObject = getBondBuy((String)parameters.get('bondOfferingId'), (String)parameters.get('investorId'), (String)parameters.get('status'), (Double)parameters.get('units'));
			if (objectType == Bond_Offering__c.getSObjectType())
				tempObject = getBondOffering((String)parameters.get('clientId'), (Double)parameters.get('interestRate'), (String)parameters.get('salesRep'));
			if (objectType == Investor__c.getSObjectType()) {
				if ((String)parameters.get('investorType') == null)
					tempObject = getInvestor();
				else
					tempObject = getInvestor((String)parameters.get('investorType'));
			}
			if (objectType == Client__c.getSObjectType())
				tempObject = getClient();
			result.add(tempObject);
		}
		return result;
	}

	public static User getTestUser(String profile) {
        Map<String,ID> profiles = new Map<String,String>();
        List<Profile> ps = [select id, name from Profile where name = :profile];
        for(Profile p : ps){
            profiles.put(p.name, p.id);
        }
        User returnUser = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName=getRandomName(), LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = profiles.get(profile), 
                TimeZoneSidKey='America/Los_Angeles', UserName=getRandomName() + '@cert501.ivan');

        return returnUser;
    }
}